# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tunnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tunelid', models.IntegerField()),
                ('src', models.CharField(max_length=30)),
                ('dst', models.CharField(max_length=30)),
                ('host', models.CharField(max_length=30)),
            ],
        ),
    ]
