# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0003_switch_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billid', models.IntegerField()),
                ('customer', models.CharField(max_length=30)),
                ('subnet_vni', models.IntegerField()),
                ('P1', models.CharField(max_length=30)),
                ('P2', models.CharField(max_length=30)),
            ],
        ),
    ]
