# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0004_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billid',
            field=models.CharField(max_length=30),
        ),
    ]
