# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0006_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnel',
            name='tunelid',
            field=models.CharField(max_length=30),
        ),
    ]
