# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0008_customer_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='linkport',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
