# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0010_vxlan'),
    ]

    operations = [
        migrations.CreateModel(
            name='L2Ethservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=30)),
                ('port', models.CharField(max_length=30)),
                ('vsi', models.CharField(max_length=30)),
                ('instance', models.CharField(max_length=30)),
                ('vlanid', models.CharField(max_length=30)),
            ],
        ),
    ]
