# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0012_l2ethservice_vxlanid'),
    ]

    operations = [
        migrations.AddField(
            model_name='l2ethservice',
            name='billid',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vxlan',
            name='billid',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
